facilitiesData = [
  {
    type: "FeatureCollection",
    name: "PFAS_facilities_geocoded",
    crs: {
      type: "name",
      properties: { name: "urn:ogc:def:crs:OGC:1.3:CRS84" },
    },
    features: [
      {
        type: "Feature",
        properties: {
          Facility: "Emerald Coast Utilities Authority",
          Address: "9255 Sturdevant St",
          City: "Pensacola",
          State: "FL",
          Zip: 32514,
          "Contact Number": "(850) 476-0480",
          "Pop Served": "255,884",
          "# PFAS detected": 7,
          PFOA: 65.0,
          PFOS: 380.0,
          "PFOA+PFOS": 445.0,
          Other: 249.0,
          "Total PFAS ppt": 694.0,
          Year: "2014-1023",
          Latitude: 30.529767,
          Longitude: -87.199073,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 9255,
          Street: "Sturdevant St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Pensacola",
          State_1: "FL",
          County: "Escambia County",
          Zip_1: 32514,
          Country: "US",
          Source: "Escambia",
        },
        geometry: { type: "Point", coordinates: [-87.199073, 30.529767] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Gonzalez Utilities Association Inc.",
          Address: "1590 Old Chemstrand Rd",
          City: "Cantonment",
          State: "FL",
          Zip: 32533,
          "Contact Number": "(850) 968-5434",
          "Pop Served": "6,356",
          "# PFAS detected": 3,
          PFOA: 17.0,
          PFOS: 9.6,
          "PFOA+PFOS": 26.6,
          Other: 3.4,
          "Total PFAS ppt": 30.0,
          Year: "2023",
          Latitude: 30.582525,
          Longitude: -87.289812,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1590,
          Street: "Old Chemstrand Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Cantonment",
          State_1: "FL",
          County: "Escambia County",
          Zip_1: 32533,
          Country: "US",
          Source: "Escambia",
        },
        geometry: { type: "Point", coordinates: [-87.289812, 30.582525] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Defuniak Springs",
          Address: "209 N 4th St",
          City: "Defuniak Springs",
          State: "FL",
          Zip: 32433,
          "Contact Number": "(850) 892-8536",
          "Pop Served": "12,243",
          "# PFAS detected": 1,
          PFOA: null,
          PFOS: 40.0,
          "PFOA+PFOS": 40.0,
          Other: 0.0,
          "Total PFAS ppt": 40.0,
          Year: "2014",
          Latitude: 30.727658,
          Longitude: -86.109322,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 209,
          Street: "4th St N",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Defuniak Springs",
          State_1: "FL",
          County: "Walton County",
          Zip_1: 32433,
          Country: "US",
          Source: "Walton County Property Appraiser",
        },
        geometry: { type: "Point", coordinates: [-86.109322, 30.727658] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Mexico Beach",
          Address: "113 22nd St",
          City: "Mexico Beach",
          State: "FL",
          Zip: 32456,
          "Contact Number": "850-648-5700",
          "Pop Served": "5,317",
          "# PFAS detected": 1,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 6.3,
          "Total PFAS ppt": 6.3,
          Year: "2023",
          Latitude: 29.945856,
          Longitude: -85.410616,
          "Accuracy Score": 0.9,
          "Accuracy Type": "rooftop",
          Number: 113,
          Street: "N 22nd St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Mexico Beach",
          State_1: "FL",
          County: "Bay County",
          Zip_1: 32456,
          Country: "US",
          Source: "Statewide2",
        },
        geometry: { type: "Point", coordinates: [-85.410616, 29.945856] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Perry Water System",
          Address: "713 N Faulkner St",
          City: "Perry",
          State: "FL",
          Zip: 32347,
          "Contact Number": "(850) 838-2326",
          "Pop Served": "8,900",
          "# PFAS detected": 2,
          PFOA: null,
          PFOS: 7.0,
          "PFOA+PFOS": 7.0,
          Other: 3.0,
          "Total PFAS ppt": 10.0,
          Year: "2023",
          Latitude: 30.121421,
          Longitude: -83.585012,
          "Accuracy Score": 1.0,
          "Accuracy Type": "range_interpolation",
          Number: 713,
          Street: "N Faulkner St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Perry",
          State_1: "FL",
          County: "Taylor County",
          Zip_1: 32347,
          Country: "US",
          Source: "TIGER/Line¬Æ dataset from the US Census Bureau",
        },
        geometry: { type: "Point", coordinates: [-83.585012, 30.121421] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Newberry Water Treatment Plant",
          Address: "1905 SW 260th St",
          City: "Newberry",
          State: "FL",
          Zip: 32669,
          "Contact Number": "(352) 472-2161",
          "Pop Served": "3,885",
          "# PFAS detected": 1,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 4.4,
          "Total PFAS ppt": 4.4,
          Year: "2023",
          Latitude: 29.635016,
          Longitude: -82.616891,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1905,
          Street: "SW 260th St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Newberry",
          State_1: "FL",
          County: "Alachua County",
          Zip_1: 32669,
          Country: "US",
          Source: "Alachua",
        },
        geometry: { type: "Point", coordinates: [-82.616891, 29.635016] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Ocala",
          Address: "1808 NE 36th Ave",
          City: "Ocala",
          State: "FL",
          Zip: 34470,
          "Contact Number": "(352) 351-6682",
          "Pop Served": "57,665",
          "# PFAS detected": 2,
          PFOA: 6.5,
          PFOS: 45.0,
          "PFOA+PFOS": 51.5,
          Other: 79.0,
          "Total PFAS ppt": 130.5,
          Year: "2022",
          Latitude: 29.206235,
          Longitude: -82.088843,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1808,
          Street: "NE 36th Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Ocala",
          State_1: "FL",
          County: "Marion County",
          Zip_1: 34470,
          Country: "US",
          Source: "Loveland",
        },
        geometry: { type: "Point", coordinates: [-82.088843, 29.206235] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Belleview",
          Address: "5343 SE Abshier Blvd",
          City: "Belleview",
          State: "FL",
          Zip: 34420,
          "Contact Number": "(352) 245-7021",
          "Pop Served": "8,433",
          "# PFAS detected": 1,
          PFOA: null,
          PFOS: 5.6,
          "PFOA+PFOS": 5.6,
          Other: 0.0,
          "Total PFAS ppt": 5.6,
          Year: "2023",
          Latitude: 29.061118,
          Longitude: -82.059379,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 5343,
          Street: "SE Abshier Blvd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Belleview",
          State_1: "FL",
          County: "Marion County",
          Zip_1: 34420,
          Country: "US",
          Source: "Loveland",
        },
        geometry: { type: "Point", coordinates: [-82.059379, 29.061118] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Little Sumter Utilities 3wps",
          Address: "984 Old Mill Run",
          City: "The Villages",
          State: "FL",
          Zip: 32162,
          "Contact Number": "352-750-0000",
          "Pop Served": "25,382",
          "# PFAS detected": 5,
          PFOA: 4.5,
          PFOS: 4.6,
          "PFOA+PFOS": 9.1,
          Other: 17.9,
          "Total PFAS ppt": 27.0,
          Year: "2023",
          Latitude: 28.908217,
          Longitude: -81.973978,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 984,
          Street: "Old Mill Run",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Lady Lake",
          State_1: "FL",
          County: "Sumter County",
          Zip_1: 32162,
          Country: "US",
          Source: "Sumter",
        },
        geometry: { type: "Point", coordinates: [-81.973978, 28.908217] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Lake Panasoffkee Water Association 2wps",
          Address: "1165 Co Rd 465",
          City: "Lake Panasoffkee",
          State: "FL",
          Zip: 33538,
          "Contact Number": "(352) 793-4236",
          "Pop Served": "4,642",
          "# PFAS detected": 8,
          PFOA: 6.7,
          PFOS: 37.0,
          "PFOA+PFOS": 43.7,
          Other: 51.3,
          "Total PFAS ppt": 95.0,
          Year: "2023",
          Latitude: 28.776937,
          Longitude: -82.12332,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1165,
          Street: "County Rd 465",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Lake Panasoffkee",
          State_1: "FL",
          County: "Sumter County",
          Zip_1: 33538,
          Country: "US",
          Source: "Sumter",
        },
        geometry: { type: "Point", coordinates: [-82.12332, 28.776937] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Eustis",
          Address: "17705 US-441",
          City: "Mt Dora",
          State: "FL",
          Zip: 32757,
          "Contact Number": "(352) 383-2131",
          "Pop Served": "35,089",
          "# PFAS detected": 4,
          PFOA: 4.9,
          PFOS: 7.5,
          "PFOA+PFOS": 12.4,
          Other: 10.6,
          "Total PFAS ppt": 23.0,
          Year: "2023",
          Latitude: 28.822236,
          Longitude: -81.665246,
          "Accuracy Score": 1.0,
          "Accuracy Type": "range_interpolation",
          Number: 17705,
          Street: "US Hwy 441",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Mount Dora",
          State_1: "FL",
          County: "Lake County",
          Zip_1: 32757,
          Country: "US",
          Source: "TIGER/Line¬Æ dataset from the US Census Bureau",
        },
        geometry: { type: "Point", coordinates: [-81.665246, 28.822236] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Mims Water Treatment / North Brevard Co.",
          Address: "1105 Buffalo Rd",
          City: "Titusville",
          State: "FL",
          Zip: 32796,
          "Contact Number": "(321) 383-5674",
          "Pop Served": "7,958",
          "# PFAS detected": 6,
          PFOA: 5.9,
          PFOS: 13.0,
          "PFOA+PFOS": 18.9,
          Other: 17.1,
          "Total PFAS ppt": 36.0,
          Year: "2023",
          Latitude: 28.623559,
          Longitude: -80.81561,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1105,
          Street: "Buffalo Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Titusville",
          State_1: "FL",
          County: "Brevard County",
          Zip_1: 32796,
          Country: "US",
          Source: "Brevard County",
        },
        geometry: { type: "Point", coordinates: [-80.81561, 28.623559] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Southlake Utilities",
          Address: "16554 Cagan Crossings Blvd #2",
          City: "Clermont",
          State: "FL",
          Zip: 34714,
          "Contact Number": "352) 394-8898",
          "Pop Served": "8,300",
          "# PFAS detected": 2,
          PFOA: null,
          PFOS: 5.1,
          "PFOA+PFOS": 5.1,
          Other: 3.0,
          "Total PFAS ppt": 8.1,
          Year: "2023",
          Latitude: 28.353851,
          Longitude: -81.679671,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 16554,
          Street: "Cagan Crossings Blvd",
          "Unit Type": "Ste",
          "Unit Number": "2",
          City_1: "Clermont",
          State_1: "FL",
          County: "Lake County",
          Zip_1: 34714,
          Country: "US",
          Source: "Public Domain Lake County",
        },
        geometry: { type: "Point", coordinates: [-81.679671, 28.353851] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Aloha Gardens Utilities",
          Address: "6915 Perrine Ranch Rd",
          City: "New Port Richey",
          State: "FL",
          Zip: 34655,
          "Contact Number": null,
          "Pop Served": "8,136",
          "# PFAS detected": 4,
          PFOA: null,
          PFOS: 32.0,
          "PFOA+PFOS": 32.0,
          Other: 20.0,
          "Total PFAS ppt": 52.0,
          Year: "2023",
          Latitude: 28.19499,
          Longitude: -82.700225,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 6915,
          Street: "Perrine Ranch Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "New Port Richey",
          State_1: "FL",
          County: "Pasco County",
          Zip_1: 34655,
          Country: "US",
          Source: "Pasco",
        },
        geometry: { type: "Point", coordinates: [-82.700225, 28.19499] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Orangewood Water System",
          Address: "9150 Curry Ford Rd",
          City: "Orlando",
          State: "FL",
          Zip: 32825,
          "Contact Number": "(407) 836-5515",
          "Pop Served": "5,937",
          "# PFAS detected": 9,
          PFOA: 26.0,
          PFOS: 81.0,
          "PFOA+PFOS": 107.0,
          Other: 78.0,
          "Total PFAS ppt": 185.0,
          Year: "2023",
          Latitude: 28.508834,
          Longitude: -81.255439,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 9150,
          Street: "Curry Ford Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Orlando",
          State_1: "FL",
          County: "Orange County",
          Zip_1: 32825,
          Country: "US",
          Source: "Public Domain Orange County",
        },
        geometry: { type: "Point", coordinates: [-81.255439, 28.508834] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Tarpon Springs Water System",
          Address: "325 Pine St",
          City: "Tarpon Springs",
          State: "FL",
          Zip: 34689,
          "Contact Number": "(727) 937-2557",
          "Pop Served": "30,415",
          "# PFAS detected": 8,
          PFOA: 9.7,
          PFOS: 37.0,
          "PFOA+PFOS": 46.7,
          Other: 46.3,
          "Total PFAS ppt": 93.0,
          Year: "2023",
          Latitude: 28.151328,
          Longitude: -82.753584,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 325,
          Street: "Pine St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Tarpon Springs",
          State_1: "FL",
          County: "Pinellas County",
          Zip_1: 34689,
          Country: "US",
          Source: "Loveland",
        },
        geometry: { type: "Point", coordinates: [-82.753584, 28.151328] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Zephyrhills",
          Address: "5335 8th St",
          City: "Zephyrhills",
          State: "FL",
          Zip: 33542,
          "Contact Number": "(813) 780-0015",
          "Pop Served": "23,097",
          "# PFAS detected": 7,
          PFOA: 7.1,
          PFOS: 160.0,
          "PFOA+PFOS": 167.1,
          Other: 169.9,
          "Total PFAS ppt": 337.0,
          Year: "2014-2023",
          Latitude: 28.23551,
          Longitude: -82.18078,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 5335,
          Street: "8th St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Zephyrhills",
          State_1: "FL",
          County: "Pasco County",
          Zip_1: 33542,
          Country: "US",
          Source: "Pasco",
        },
        geometry: { type: "Point", coordinates: [-82.18078, 28.23551] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Hcpud/pebble Creek Subdivision",
          Address: "925 E Twiggs St.",
          City: "Tampa",
          State: "FL",
          Zip: 33602,
          "Contact Number": "(813) 272-5977",
          "Pop Served": "5,411",
          "# PFAS detected": 4,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 17.0,
          "Total PFAS ppt": 17.0,
          Year: "2023",
          Latitude: 27.951377,
          Longitude: -82.451308,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 925,
          Street: "E Twiggs St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Tampa",
          State_1: "FL",
          County: "Hillsborough County",
          Zip_1: 33602,
          Country: "US",
          Source: "Hillsborough County CC BY 4.0",
        },
        geometry: { type: "Point", coordinates: [-82.451308, 27.951377] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Tampa Water Department",
          Address: "7125 N 30th St",
          City: "Tampa",
          State: "FL",
          Zip: 33610,
          "Contact Number": "(813) 231-5238",
          "Pop Served": "645,000",
          "# PFAS detected": 5,
          PFOA: null,
          PFOS: 4.0,
          "PFOA+PFOS": 4.0,
          Other: 18.0,
          "Total PFAS ppt": 22.0,
          Year: "2023",
          Latitude: 28.016073,
          Longitude: -82.424646,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 7125,
          Street: "N 30th St",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Tampa",
          State_1: "FL",
          County: "Hillsborough County",
          Zip_1: 33610,
          Country: "US",
          Source: "Hillsborough County CC BY 4.0",
        },
        geometry: { type: "Point", coordinates: [-82.424646, 28.016073] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Seaboard Utilities",
          Address: "306 E Jackson St #5E",
          City: "Tampa",
          State: "FL",
          Zip: 33602,
          "Contact Number": "813-274-8811",
          "Pop Served": "13,707",
          "# PFAS detected": 7,
          PFOA: null,
          PFOS: 5.2,
          "PFOA+PFOS": 5.2,
          Other: 33.8,
          "Total PFAS ppt": 39.0,
          Year: "2023",
          Latitude: 27.94727,
          Longitude: -82.4574,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 306,
          Street: "E Jackson St",
          "Unit Type": "#",
          "Unit Number": "5E",
          City_1: "Tampa",
          State_1: "FL",
          County: "Hillsborough County",
          Zip_1: 33602,
          Country: "US",
          Source: "Hillsborough County CC BY 4.0",
        },
        geometry: { type: "Point", coordinates: [-82.4574, 27.94727] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "MacDill Air Force Base",
          Address: "6901 S Dale Mabry Hwy",
          City: "Tampa",
          State: "FL",
          Zip: 33621,
          "Contact Number": null,
          "Pop Served": "11,965",
          "# PFAS detected": 6,
          PFOA: null,
          PFOS: 5.4,
          "PFOA+PFOS": 5.4,
          Other: 24.6,
          "Total PFAS ppt": 30.0,
          Year: "2023",
          Latitude: 27.867878,
          Longitude: -82.506899,
          "Accuracy Score": 0.99,
          "Accuracy Type": "rooftop",
          Number: 6901,
          Street: "S Dale Mabry Hwy",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Tampa",
          State_1: "FL",
          County: "Hillsborough County",
          Zip_1: 33611,
          Country: "US",
          Source: "Hillsborough County CC BY 4.0",
        },
        geometry: { type: "Point", coordinates: [-82.506899, 27.867878] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Bradenton",
          Address: "5800 Natalie Way E",
          City: "Bradenton",
          State: "FL",
          Zip: 34203,
          "Contact Number": "(941) 727-6360",
          "Pop Served": "54,409",
          "# PFAS detected": 4,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 24.0,
          "Total PFAS ppt": 24.0,
          Year: "2023",
          Latitude: 27.441957,
          Longitude: -82.493325,
          "Accuracy Score": 1.0,
          "Accuracy Type": "range_interpolation",
          Number: 5800,
          Street: "Natalie Way E",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Bradenton",
          State_1: "FL",
          County: "Manatee County",
          Zip_1: 34203,
          Country: "US",
          Source: "TIGER/Line¬Æ dataset from the US Census Bureau",
        },
        geometry: { type: "Point", coordinates: [-82.493325, 27.441957] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "North Hutchinson Island",
          Address: "2300 Virginia Avenue",
          City: "Fort Pierce",
          State: "FL",
          Zip: 34982,
          "Contact Number": "772-462-1100",
          "Pop Served": "3,954",
          "# PFAS detected": 3,
          PFOA: null,
          PFOS: 9.0,
          "PFOA+PFOS": 9.0,
          Other: 7.0,
          "Total PFAS ppt": 16.0,
          Year: "2023",
          Latitude: 27.426365,
          Longitude: -80.347989,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 2300,
          Street: "Virginia Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Fort Pierce",
          State_1: "FL",
          County: "St. Lucie County",
          Zip_1: 34982,
          Country: "US",
          Source: "St Lucie",
        },
        geometry: { type: "Point", coordinates: [-80.347989, 27.426365] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Stuart - Water Plant",
          Address: "1000 SE Palm Beach Rd",
          City: "Stuart",
          State: "FL",
          Zip: 34994,
          "Contact Number": "(772) 288-5343",
          "Pop Served": "19,000",
          "# PFAS detected": 3,
          PFOA: null,
          PFOS: 180.0,
          "PFOA+PFOS": 180.0,
          Other: 106.0,
          "Total PFAS ppt": 286.0,
          Year: "2014-2015",
          Latitude: 27.189029,
          Longitude: -80.238665,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1000,
          Street: "SE Palm Beach Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Stuart",
          State_1: "FL",
          County: "Martin County",
          Zip_1: 34994,
          Country: "US",
          Source: "Martin",
        },
        geometry: { type: "Point", coordinates: [-80.238665, 27.189029] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Okeechobee Utility Authority",
          Address: "100 SW 5th Ave",
          City: "Okeechobee",
          State: "FL",
          Zip: 34974,
          "Contact Number": "(863) 763-9460",
          "Pop Served": "20,000",
          "# PFAS detected": 4,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 26.0,
          "Total PFAS ppt": 26.0,
          Year: "2023",
          Latitude: 27.24314,
          Longitude: -80.83447,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 100,
          Street: "SW 5th Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Okeechobee",
          State_1: "FL",
          County: "Okeechobee County",
          Zip_1: 34974,
          Country: "US",
          Source: "Okeechobee",
        },
        geometry: { type: "Point", coordinates: [-80.83447, 27.24314] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Indiantown Company",
          Address: "15851 SW Farm Rd",
          City: "Indiantown",
          State: "FL",
          Zip: 34956,
          "Contact Number": "772) 597-2121",
          "Pop Served": "5,847",
          "# PFAS detected": 1,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 8.0,
          "Total PFAS ppt": 8.0,
          Year: "2023",
          Latitude: 27.019397,
          Longitude: -80.469247,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 15851,
          Street: "SW Farm Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Indiantown",
          State_1: "FL",
          County: "Martin County",
          Zip_1: 34956,
          Country: "US",
          Source: "Martin",
        },
        geometry: { type: "Point", coordinates: [-80.469247, 27.019397] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Lee County Utilities",
          Address: "7391 College Pkwy",
          City: "Fort Myers",
          State: "FL",
          Zip: 33907,
          "Contact Number": "(239) 533-8845",
          "Pop Served": "251,502",
          "# PFAS detected": 5,
          PFOA: null,
          PFOS: null,
          "PFOA+PFOS": 0.0,
          Other: 34.0,
          "Total PFAS ppt": 34.0,
          Year: "2023",
          Latitude: 26.554854,
          Longitude: -81.878214,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 7391,
          Street: "College Pkwy",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Fort Myers",
          State_1: "FL",
          County: "Lee County",
          Zip_1: 33907,
          Country: "US",
          Source: "Indemnification",
        },
        geometry: { type: "Point", coordinates: [-81.878214, 26.554854] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Immokalee Water",
          Address: "1020 Sanitation Rd",
          City: "Immokalee",
          State: "FL",
          Zip: 34142,
          "Contact Number": "(239) 658-3630",
          "Pop Served": "25,608",
          "# PFAS detected": 3,
          PFOA: 4.2,
          PFOS: 12.0,
          "PFOA+PFOS": 16.2,
          Other: 4.8,
          "Total PFAS ppt": 21.0,
          Year: "2023",
          Latitude: 26.410868,
          Longitude: -81.427242,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1020,
          Street: "Sanitation Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Immokalee",
          State_1: "FL",
          County: "Collier County",
          Zip_1: 34142,
          Country: "US",
          Source: "Public Domain Collier County",
        },
        geometry: { type: "Point", coordinates: [-81.427242, 26.410868] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Florida Governmental Utility Authority",
          Address: "9841 Bernwood Place Drive",
          City: "Fort Myers",
          State: "FL",
          Zip: 33966,
          "Contact Number": "(239) 543-1005",
          "Pop Served": "29,656",
          "# PFAS detected": 4,
          PFOA: null,
          PFOS: 11.0,
          "PFOA+PFOS": 11.0,
          Other: 12.0,
          "Total PFAS ppt": 23.0,
          Year: "2023",
          Latitude: 26.599324,
          Longitude: -81.811805,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 9841,
          Street: "Bernwood Place Dr",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Fort Myers",
          State_1: "FL",
          County: "Lee County",
          Zip_1: 33966,
          Country: "US",
          Source: "Indemnification",
        },
        geometry: { type: "Point", coordinates: [-81.811805, 26.599324] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Lauderhill",
          Address: "2101 NW 49th Ave",
          City: "Lauderhill",
          State: "FL",
          Zip: 33313,
          "Contact Number": "(954) 730-2960",
          "Pop Served": "55,000",
          "# PFAS detected": 14,
          PFOA: 10.4,
          PFOS: 47.0,
          "PFOA+PFOS": 57.4,
          Other: 31.8,
          "Total PFAS ppt": 89.2,
          Year: "2020",
          Latitude: 26.152815,
          Longitude: -80.21831,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 2101,
          Street: "NW 49th Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Lauderhill",
          State_1: "FL",
          County: "Broward County",
          Zip_1: 33313,
          Country: "US",
          Source: "Broward",
        },
        geometry: { type: "Point", coordinates: [-80.21831, 26.152815] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "City of Pembroke Pines",
          Address: "13955 Pembroke Rd",
          City: "Pembroke Pines",
          State: "FL",
          Zip: 33029,
          "Contact Number": "(954) 435-6721",
          "Pop Served": "168,600",
          "# PFAS detected": 9,
          PFOA: 14.0,
          PFOS: 35.0,
          "PFOA+PFOS": 49.0,
          Other: 123.0,
          "Total PFAS ppt": 172.0,
          Year: "2023",
          Latitude: 25.993236,
          Longitude: -80.331801,
          "Accuracy Score": 0.9,
          "Accuracy Type": "rooftop",
          Number: 13955,
          Street: "Pembroke Rd",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Pembroke Pines",
          State_1: "FL",
          County: "Broward County",
          Zip_1: 33027,
          Country: "US",
          Source: "Statewide2",
        },
        geometry: { type: "Point", coordinates: [-80.331801, 25.993236] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Miramar (East & West) Plants",
          Address: "2600 SW 66th Terrace",
          City: "Miramar",
          State: "FL",
          Zip: 33023,
          "Contact Number": "(954) 602-3896",
          "Pop Served": "127,700",
          "# PFAS detected": 2,
          PFOA: 21.0,
          PFOS: 47.0,
          "PFOA+PFOS": 68.0,
          Other: 0.0,
          "Total PFAS ppt": 68.0,
          Year: "2014",
          Latitude: 25.986049,
          Longitude: -80.220888,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 2600,
          Street: "SW 66th Ter",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Miramar",
          State_1: "FL",
          County: "Broward County",
          Zip_1: 33023,
          Country: "US",
          Source: "MapWise (and individual Florida counties)",
        },
        geometry: { type: "Point", coordinates: [-80.220888, 25.986049] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Miami Dade Water and Sewer Authority - Orr Plant",
          Address: "6800 SW 87th Ave",
          City: "Miami",
          State: "FL",
          Zip: 33173,
          "Contact Number": "(305) 665-7477",
          "Pop Served": "2,300,000",
          "# PFAS detected": 12,
          PFOA: 4.2,
          PFOS: 12.0,
          "PFOA+PFOS": 16.2,
          Other: 33.3,
          "Total PFAS ppt": 49.5,
          Year: "2023",
          Latitude: 25.704912,
          Longitude: -80.334612,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 6800,
          Street: "SW 87th Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Miami",
          State_1: "FL",
          County: "Miami-Dade County",
          Zip_1: 33173,
          Country: "US",
          Source: "Public Domain Miami-Dade County",
        },
        geometry: { type: "Point", coordinates: [-80.334612, 25.704912] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Miami Dade Water and Sewer Authority - Preston Plant",
          Address: "1100 W 2nd Ave",
          City: "Hialeah",
          State: "FL",
          Zip: 33010,
          "Contact Number": "(305) 665-7477",
          "Pop Served": "2,300,000",
          "# PFAS detected": 12,
          PFOA: 4.0,
          PFOS: 14.0,
          "PFOA+PFOS": 18.0,
          Other: 35.05,
          "Total PFAS ppt": 53.05,
          Year: "2023",
          Latitude: 25.831771,
          Longitude: -80.286668,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 1100,
          Street: "W 2nd Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Hialeah",
          State_1: "FL",
          County: "Miami-Dade County",
          Zip_1: 33010,
          Country: "US",
          Source: "Public Domain Miami-Dade County",
        },
        geometry: { type: "Point", coordinates: [-80.286668, 25.831771] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Miami Dade Water and Sewer Authority - Hialeah Plant",
          Address: "700 W 2nd Ave",
          City: "Hialeah",
          State: "FL",
          Zip: 33010,
          "Contact Number": "(305) 665-7477",
          "Pop Served": "2,300,000",
          "# PFAS detected": 14,
          PFOA: 9.5,
          PFOS: 28.0,
          "PFOA+PFOS": 37.5,
          Other: 243.66,
          "Total PFAS ppt": 281.16,
          Year: "2023",
          Latitude: 25.828375,
          Longitude: -80.286773,
          "Accuracy Score": 1.0,
          "Accuracy Type": "rooftop",
          Number: 700,
          Street: "W 2nd Ave",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Hialeah",
          State_1: "FL",
          County: "Miami-Dade County",
          Zip_1: 33010,
          Country: "US",
          Source: "Public Domain Miami-Dade County",
        },
        geometry: { type: "Point", coordinates: [-80.286773, 25.828375] },
      },
      {
        type: "Feature",
        properties: {
          Facility: "Florida Keys Aquaduct Authority",
          Address: "91620 Overseas Hwy",
          City: "Tavernier",
          State: "FL ",
          Zip: 33070,
          "Contact Number": "(305) 296-2454",
          "Pop Served": null,
          "# PFAS detected": 18,
          PFOA: 1.6,
          PFOS: 39,
          "PFOA+PFOS": 40.6,
          Other: 0.0,
          "Total PFAS ppt": 91.07,
          Year: "2023",
          Latitude: 25.006166,
          Longitude: -80.519963,
          "Accuracy Score": 0.9,
          "Accuracy Type": "range_interpolation",
          Number: 91620,
          Street: "Overseas Hwy",
          "Unit Type": null,
          "Unit Number": null,
          City_1: "Tavernier",
          State_1: "FL",
          County: "Monroe County",
          Zip_1: 33070,
          Country: "US",
          Source: "TIGER/Line¬Æ dataset from the US Census Bureau",
        },
        geometry: { type: "Point", coordinates: [-80.519963, 25.006166] },
      },
    ],
  },
];
